### ISSUE TITLE
Wrong package names in the article

### ISSUE THREAD

**Issue by IAmRaszagal** [IvanJov/react-rxjs-github-search#1]
Hi, 
I just wanted to say that in the article it says to run 
"yarn add redux redux-react rxjs redux-observables"
but it should be 
"yarn add redux react-redux rxjs redux-observable"

Other than that, thanks for a great introduction to redux observable. Just what I needed :)

**Comment by IvanJov** [comment]
Ah sorry for that, it's fixed! Thanks for letting me know. And I am glad that you like it 😄
